import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--disable-dev-shm-usage'] });
const page = await browser.newPage({ viewport: { width: 480, height: 300 } });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
page.setDefaultTimeout(400000);
await page.addInitScript(() => { localStorage.setItem('onitama.quality', 'low'); localStorage.setItem('onitama.muted', '1'); });
await page.goto('http://localhost:4173/');
await page.waitForFunction(() => window.__onitama, null, { polling: 1000 });
await page.bringToFront();
const sample = () => page.evaluate(() => ({ ...window.__onitama.pace, autoRotate: window.__onitama.stage.controls.autoRotate, focus: document.hasFocus() }));
await page.waitForTimeout(4000);
console.log('menu idle (auto-rotating):', JSON.stringify(await sample()));
await page.evaluate(() => window.__onitama.stage.controls.dispatchEvent({ type: 'start' }));
await page.waitForTimeout(1500);
console.log('during drag:', JSON.stringify(await sample()));
await page.evaluate(() => window.__onitama.stage.controls.dispatchEvent({ type: 'end' }));
await page.waitForTimeout(5000);
console.log('after drag + grace:', JSON.stringify(await sample()));
await browser.close();
